---
name: CI

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

env:
  DEBIAN_FRONTEND: noninteractive

# Note: ca-certificates and git are needed for actions/checkout to use git
# which is needed for codecov/codecov-action.

jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo snap install ruff
      - name: Run linter tests
        run: |
          ruff check --preview .

  # TODO: reenable that after cleaning everything. Those tests are nowhere
  # near ready to be run again, and will likely just get replaced once bigger
  # refactoring will have occured.
  # tests:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       container:
  #         - ubuntu:latest
  #         - ubuntu:rolling
  #   container:
  #     image: ${{ matrix.container }}
  #   steps:
  #     - name: Sanitize container name (for artifact name)
  #       run: |
  #         container=$(echo "${{ matrix.container }}" | sed 's/:/-/')
  #         echo "JOB=${GITHUB_JOB}-${container}" >> "$GITHUB_ENV"
  #     - name: Install dependencies
  #       run: >
  #         apt-get update
  #         && apt-get install --no-install-recommends --yes
  #         apport-retrace git python3-amqp python3-cassandra python3-pygit2
  #         python3-swiftclient ubuntu-dbgsym-keyring
  #     - name: Run unit and integration tests
  #       run: >
  #         python3 -m pytest -ra --cov=$(pwd) --cov-branch --cov-report=xml
  #         --durations=0 src/test
  #     - name: Upload coverage
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: coverage-${{ env.JOB }}
  #         path: ./coverage*.xml

  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: woke
        uses: get-woke/woke-action@b2ec032c4a2c912142b38a6a453ad62017813ed0 # v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: true
